# Generated by Django 3.0.6 on 2020-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.TextField(max_length=500)),
                ('minute', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('actors', models.ManyToManyField(to='movies.Actor')),
                ('categories', models.ManyToManyField(to='movies.Category')),
            ],
        ),
    ]
